<#
.SYNOPSIS
    This script takes the TSV list of hosts generated by Hyena and outputs the 'ComputerName' column only.  This can be used as input to NirSoft's USBDeview.
.DESCRIPTION
    The script extracts the 'ComputerName' of systems generated from Hyena. It outputs the list as a text file in ASCII which can be used as input via the /remotefile option in NirSoft's USBDeview software.
.PARAMETER TsvData
    The host TSV file listing generated from Hyena.
.NOTES
    Version 1.0
    Sam Pursglove
    Last modified: 16 JULY 2018
.EXAMPLE
    Extract-UsbdeviewTargets.ps1 .\machines.tsv
#>

Param 
(
    [Parameter(Position=0,
               Mandatory=$true,
               ValueFromPipeline=$false,
               HelpMessage='TSV filename of the Hyena generated listing of computers.')]
    [string]$TsvFile
)

$TsvData = Import-Csv $TsvFile -Delimiter `t

$getHostname = $TsvData | Select-Object -ExpandProperty 'ComputerName' -Unique | Out-File targets.txt -Encoding ascii